
[order]
menu_config_type = "Infra FE and BE with Automate"
menu_order_num = "3"

[order.automate]
server = "Ubuntu/18.04"
version = "Latest"

[order.habitat]
required = "no"
server = "Ubuntu/18.04"

[order.infa_server]
server = "Ubuntu/18.04"
version = "Latest"

[order.nodes]
count = "2"
server = "Ubuntu/18.04"
version = "Latest"

[order.server]
type = "Ubuntu"
version = "18.04"
